//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XsdDocumentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XsdDocumentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error reading the schema file &apos;{0}&apos;..
        /// </summary>
        internal static string ExceptionBuilderCannotReadSchemaFile {
            get {
                return ResourceManager.GetString("ExceptionBuilderCannotReadSchemaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error reading the inline documentation XSLT file &apos;{0}&apos;..
        /// </summary>
        internal static string ExceptionBuilderCannotReadTransform {
            get {
                return ResourceManager.GetString("ExceptionBuilderCannotReadTransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error constructing the schema set..
        /// </summary>
        internal static string ExceptionBuilderErrorBuildingSchemaSet {
            get {
                return ResourceManager.GetString("ExceptionBuilderErrorBuildingSchemaSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error reading the external documentation file &apos;{0}&apos;..
        /// </summary>
        internal static string ExceptionBuilderErrorReadingExternalDocumentation {
            get {
                return ResourceManager.GetString("ExceptionBuilderErrorReadingExternalDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error transforming the inline documentation contained in the XML schema file &apos;{0}&apos;..
        /// </summary>
        internal static string ExceptionBuilderErrorTransformingInlineDocumentation {
            get {
                return ResourceManager.GetString("ExceptionBuilderErrorTransformingInlineDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected schema object type &apos;{0}&apos;..
        /// </summary>
        internal static string ExceptionBuilderUnexpectedSchemaObjectType {
            get {
                return ResourceManager.GetString("ExceptionBuilderUnexpectedSchemaObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled case label &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionBuilderUnhandledCaseLabel {
            get {
                return ResourceManager.GetString("ExceptionBuilderUnhandledCaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute group &apos;{0}&apos; cannot be extended with attribute &apos;{1}&apos; as &apos;{0}&apos; does not contain an xs:anyAttribute element..
        /// </summary>
        internal static string ProblemReporterAttributeParentAttributGroupOffersNoExtension {
            get {
                return ResourceManager.GetString("ProblemReporterAttributeParentAttributGroupOffersNoExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The complex type &apos;{0}&apos; cannot be extended with attribute &apos;{1}&apos; as &apos;{0}&apos; does not contain an xs:anyAttribute element..
        /// </summary>
        internal static string ProblemReporterAttributeParentComplexTypeOffersNoExtension {
            get {
                return ResourceManager.GetString("ProblemReporterAttributeParentComplexTypeOffersNoExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element &apos;{0}&apos; cannot be extended with attribute &apos;{1}&apos; as &apos;{0}&apos; does not contain an xs:anyAttribute element..
        /// </summary>
        internal static string ProblemReporterAttributeParentElementOffersNoExtension {
            get {
                return ResourceManager.GetString("ProblemReporterAttributeParentElementOffersNoExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The complex type &apos;{0}&apos; cannot be extended with element &apos;{1}&apos; as &apos;{0}&apos; does not contain an xs:any element..
        /// </summary>
        internal static string ProblemReporterElementParentComplexTypeOffersNoExtension {
            get {
                return ResourceManager.GetString("ProblemReporterElementParentComplexTypeOffersNoExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element &apos;{0}&apos; cannot be extended with element &apos;{1}&apos; as &apos;{0}&apos; does not contain an xs:any element..
        /// </summary>
        internal static string ProblemReporterElementParentElementOffersNoExtension {
            get {
                return ResourceManager.GetString("ProblemReporterElementParentElementOffersNoExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group &apos;{0}&apos; cannot be extended with element &apos;{1}&apos; as &apos;{0}&apos; does not contain an xs:any element..
        /// </summary>
        internal static string ProblemReporterElementParentGroupOffersNoExtension {
            get {
                return ResourceManager.GetString("ProblemReporterElementParentGroupOffersNoExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; entity cannot be used as an extension. The only valid extension types are &apos;Element&apos; and &apos;Attribute&apos;..
        /// </summary>
        internal static string ProblemReporterInvalidExtensionType {
            get {
                return ResourceManager.GetString("ProblemReporterInvalidExtensionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external doc file &apos;{0}&apos; contains a member URI with a value of &apos;##Namespace&apos; although the doc file was marked as documenting the schema set..
        /// </summary>
        internal static string ProblemReporterInvalidNamespaceUriInSchemaSet {
            get {
                return ResourceManager.GetString("ProblemReporterInvalidNamespaceUriInSchemaSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URI &apos;{0}&apos; is used to indicate a preferred alternative over an obsolete entity but does not refer to a valid XML entity..
        /// </summary>
        internal static string ProblemReporterInvalidObsoleteUri {
            get {
                return ResourceManager.GetString("ProblemReporterInvalidObsoleteUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; entity type cannot be used as the parent for an element extension. The only valid parent types are &apos;Element&apos;, &apos;Group&apos;, and &apos;ComplexType&apos;..
        /// </summary>
        internal static string ProblemReporterInvalidParentForExtension {
            get {
                return ResourceManager.GetString("ProblemReporterInvalidParentForExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; entity type cannot be used as the parent for an attribute extension. The only valid parent types are &apos;Element&apos;, &apos;AttributeGroup&apos;, and &apos;ComplexType&apos;..
        /// </summary>
        internal static string ProblemReporterInvalidParentForExtension1 {
            get {
                return ResourceManager.GetString("ProblemReporterInvalidParentForExtension1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URI &apos;{0}&apos; is used to indicate an extension parent but does not refer to a valid XML entity..
        /// </summary>
        internal static string ProblemReporterInvalidParentUri {
            get {
                return ResourceManager.GetString("ProblemReporterInvalidParentUri", resourceCulture);
            }
        }
    }
}
