//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XsdDocumentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XsdDocumentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;topic id=&quot;${TopicId}&quot; revisionNumber=&quot;1&quot;&gt;
        ///	&lt;developerConceptualDocument xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;
        ///								 xmlns:ddue=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;
        ///								 xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;
        ///
        ///		&lt;introduction&gt;
        ///			&lt;para&gt;
        ///				${Summary}
        ///			&lt;/para&gt;
        ///			&lt;markup&gt;
        ///				&lt;p /&gt;
        ///				&lt;b&gt;Namespace:&lt;/b&gt; ${Namespace}&lt;br/&gt;
        ///				&lt;b&gt;Schema:&lt;/b&gt; ${Schema}&lt;br/&gt;
        ///			&lt;/markup&gt;
        ///		&lt;/introduction&gt;
        ///
        ///		&lt;section addre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AttributeGroupTopic {
            get {
                return ResourceManager.GetString("AttributeGroupTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;topic id=&quot;${TopicId}&quot; revisionNumber=&quot;1&quot;&gt;
        ///	&lt;developerConceptualDocument xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;
        ///								 xmlns:ddue=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;
        ///								 xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;
        ///
        ///		&lt;introduction&gt;
        ///			&lt;para&gt;
        ///				${Summary}
        ///			&lt;/para&gt;
        ///			&lt;markup&gt;
        ///				&lt;p /&gt;
        ///				&lt;b&gt;Namespace:&lt;/b&gt; ${Namespace}&lt;br/&gt;
        ///				&lt;b&gt;Schema:&lt;/b&gt; ${Schema}&lt;br/&gt;
        ///			&lt;/markup&gt;
        ///		&lt;/introduction&gt;
        ///
        ///		&lt;section addre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AttributeTopic {
            get {
                return ResourceManager.GetString("AttributeTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;topic id=&quot;${TopicId}&quot; revisionNumber=&quot;1&quot;&gt;
        ///	&lt;developerConceptualDocument xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;
        ///								 xmlns:ddue=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;
        ///								 xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;
        ///
        ///		&lt;introduction&gt;
        ///			&lt;para&gt;
        ///				${Summary}
        ///			&lt;/para&gt;
        ///			&lt;markup&gt;
        ///				&lt;p /&gt;
        ///				&lt;b&gt;Namespace:&lt;/b&gt; ${Namespace}&lt;br/&gt;
        ///				&lt;b&gt;Schema:&lt;/b&gt; ${Schema}&lt;br/&gt;
        ///			&lt;/markup&gt;
        ///		&lt;/introduction&gt;
        ///
        ///		&lt;section addre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ComplexTypeTopic {
            get {
                return ResourceManager.GetString("ComplexTypeTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;topic id=&quot;${TopicId}&quot; revisionNumber=&quot;1&quot;&gt;
        ///	&lt;developerConceptualDocument xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;
        ///								 xmlns:ddue=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;
        ///								 xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;
        ///
        ///		&lt;introduction&gt;
        ///			&lt;para&gt;
        ///				${Summary}
        ///			&lt;/para&gt;
        ///			&lt;markup&gt;
        ///				&lt;p /&gt;
        ///				&lt;b&gt;Namespace:&lt;/b&gt; ${Namespace}&lt;br/&gt;
        ///				&lt;b&gt;Schema:&lt;/b&gt; ${Schema}&lt;br/&gt;
        ///			&lt;/markup&gt;
        ///		&lt;/introduction&gt;
        ///
        ///		&lt;section addre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ElementTopic {
            get {
                return ResourceManager.GetString("ElementTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;topic id=&quot;${TopicId}&quot; revisionNumber=&quot;1&quot;&gt;
        ///	&lt;developerConceptualDocument xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;
        ///								 xmlns:ddue=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;
        ///								 xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;
        ///
        ///		&lt;introduction&gt;
        ///			&lt;para&gt;
        ///				${Summary}
        ///			&lt;/para&gt;
        ///			&lt;markup&gt;
        ///				&lt;p /&gt;
        ///				&lt;b&gt;Namespace:&lt;/b&gt; ${Namespace}&lt;br/&gt;
        ///				&lt;b&gt;Schema:&lt;/b&gt; ${Schema}&lt;br/&gt;
        ///			&lt;/markup&gt;
        ///		&lt;/introduction&gt;
        ///
        ///		&lt;section addre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GroupTopic {
            get {
                return ResourceManager.GetString("GroupTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;topic id=&quot;${TopicId}&quot; revisionNumber=&quot;1&quot;&gt;
        ///	&lt;developerConceptualDocument xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;
        ///							 xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;
        ///
        ///		&lt;introduction&gt;
        ///			${Summary}
        ///		&lt;/introduction&gt;
        ///
        ///		&lt;section address=&quot;remarks&quot;&gt;
        ///			&lt;title&gt;Remarks&lt;/title&gt;
        ///			&lt;content&gt;
        ///				${Remarks}
        ///			&lt;/content&gt;
        ///		&lt;/section&gt;
        ///
        ///		${RootSchemaSection}
        ///		${RootElementSection}
        ///		${SchemaSection}
        ///		${ElementSection}
        ///		${AttributeSection [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NamespaceTopic {
            get {
                return ResourceManager.GetString("NamespaceTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;topic id=&quot;${TopicId}&quot; revisionNumber=&quot;1&quot;&gt;
        ///	&lt;developerConceptualDocument xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;
        ///							 xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;
        ///		&lt;introduction&gt;
        ///			&lt;markup&gt;
        ///				&lt;p&gt;The ${Namespace} namespace exposes the following members.&lt;/p&gt;
        ///			&lt;/markup&gt;
        ///		&lt;/introduction&gt;
        ///		${ItemSection}
        ///	&lt;/developerConceptualDocument&gt;
        ///&lt;/topic&gt;.
        /// </summary>
        internal static string OverviewTopic {
            get {
                return ResourceManager.GetString("OverviewTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;topic id=&quot;${TopicId}&quot; revisionNumber=&quot;1&quot;&gt;
        ///	&lt;developerConceptualDocument xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;
        ///							 xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;
        ///
        ///		&lt;introduction&gt;
        ///			${Summary}
        ///		&lt;/introduction&gt;
        ///
        ///		&lt;section address=&quot;remarks&quot;&gt;
        ///			&lt;title&gt;Remarks&lt;/title&gt;
        ///			&lt;content&gt;
        ///				${Remarks}
        ///			&lt;/content&gt;
        ///		&lt;/section&gt;
        ///
        ///		${NamespaceSection}
        ///	&lt;/developerConceptualDocument&gt;
        ///&lt;/topic&gt;.
        /// </summary>
        internal static string SchemaSetTopic {
            get {
                return ResourceManager.GetString("SchemaSetTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;topic id=&quot;${TopicId}&quot; revisionNumber=&quot;1&quot;&gt;
        ///	&lt;developerConceptualDocument xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;
        ///							 xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;
        ///		&lt;introduction&gt;
        ///			${Summary}
        ///			&lt;markup&gt;
        ///				&lt;p /&gt;
        ///				&lt;b&gt;Namespace:&lt;/b&gt; ${Namespace}&lt;br/&gt;
        ///			&lt;/markup&gt;
        ///		&lt;/introduction&gt;
        ///
        ///		&lt;section address=&quot;remarks&quot;&gt;
        ///			&lt;title&gt;Remarks&lt;/title&gt;
        ///			&lt;content&gt;
        ///				${Remarks}
        ///			&lt;/content&gt;
        ///		&lt;/section&gt;
        ///
        ///		${ElementSection}
        ///		${Attribut [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SchemaTopic {
            get {
                return ResourceManager.GetString("SchemaTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;topic id=&quot;${TopicId}&quot; revisionNumber=&quot;1&quot;&gt;
        ///	&lt;developerConceptualDocument xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;
        ///								 xmlns:ddue=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;
        ///								 xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;
        ///
        ///		&lt;introduction&gt;
        ///			&lt;para&gt;
        ///				${Summary}
        ///			&lt;/para&gt;
        ///			&lt;markup&gt;
        ///				&lt;p /&gt;
        ///				&lt;b&gt;Namespace:&lt;/b&gt; ${Namespace}&lt;br/&gt;
        ///				&lt;b&gt;Schema:&lt;/b&gt; ${Schema}&lt;br/&gt;
        ///			&lt;/markup&gt;
        ///		&lt;/introduction&gt;
        ///
        ///		&lt;section addre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SimpleTypeTopic {
            get {
                return ResourceManager.GetString("SimpleTypeTopic", resourceCulture);
            }
        }
    }
}
